/* ==========================================================================
   Choicease — exporters.js
   JSON (re-importable), CSV, board-ready PDF, and QR (legacy-compatible
   chunk format: {"i","t","v":"1.1"}|<base64 of deflated JSON>).
   External libs (loaded via <script>): pako, QRCode, jspdf (+autotable), jsQR.
   ========================================================================== */

import { decision, exportSnapshot } from './state.js';
import { RATING_LABELS } from './engine.js';
import { verdictSentence } from './narrative.js';
import { toast, downloadBlob, safeFilename } from './ui.js';

/* ------------------------------- JSON ------------------------------------ */

export function exportJSON() {
  const snapshot = exportSnapshot();
  const blob = new Blob([JSON.stringify(snapshot, null, 2)], { type: 'application/json' });
  downloadBlob(blob, safeFilename(decision.title, 'json'));
  toast('Decision saved as JSON.');
}

/* -------------------------------- CSV ------------------------------------ */

export function exportCSV(analysis) {
  const { ranked } = analysis;
  const q = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const rows = [];

  rows.push(`Decision Analysis:,${q(decision.title)}`);
  rows.push(`Context:,${q(decision.description || 'N/A')}`);
  rows.push(`Generated:,${q(new Date().toLocaleString())}`);
  rows.push(`Generated by:,${q('Choicease — choicease.com')}`);
  rows.push('');

  rows.push('SUMMARY RESULTS');
  rows.push('Rank,Option,Description,Final Score,Score %');
  for (const r of ranked) {
    rows.push([r.rank, q(r.option.name), q(r.option.description), r.totalScore.toFixed(2),
      `${Math.round((r.totalScore / 5) * 100)}%`].join(','));
  }
  rows.push('');

  rows.push('CRITERIA WEIGHTS');
  rows.push('Criterion,Weight,Description');
  for (const c of decision.criteria) {
    rows.push([q(c.name), `${Math.round(decision.normalizedWeights[c.id] || 0)}%`,
      q(c.description || 'N/A')].join(','));
  }
  rows.push('');

  rows.push('DETAILED RATINGS MATRIX');
  let header = 'Option,Description,Final Score';
  for (const c of decision.criteria) {
    header += `,${q(`${c.name} (Rating)`)},${q(`${c.name} (Weight)`)},${q(`${c.name} (Weighted)`)}`;
  }
  rows.push(header);
  for (const r of ranked) {
    let row = `${q(r.option.name)},${q(r.option.description)},${r.totalScore.toFixed(2)}`;
    for (const c of decision.criteria) {
      const cell = r.criteriaScores[c.id];
      row += cell
        ? `,${cell.rating.toFixed(1)},${Math.round(cell.weightPct)}%,${cell.weighted.toFixed(3)}`
        : ',N/A,N/A,N/A';
    }
    rows.push(row);
  }
  rows.push('');

  rows.push('METHODOLOGY');
  rows.push(`Scoring Method,${q('Weighted Multi-Criteria Decision Analysis')}`);
  rows.push(`Rating Scale,${q('0-5 (0=Unacceptable, 1=Poor, 2=Fair, 3=Good, 4=Very good, 5=Excellent)')}`);
  rows.push(`Weight Calculation,${q('Importance 1-5 mapped geometrically (1, 1.78, 3.16, 5.62, 10) and normalized to 100%')}`);
  rows.push(`Final Score Formula,${q('Sum of (rating x normalized weight) per option')}`);

  const blob = new Blob([`\uFEFF${rows.join('\n')}`], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, safeFilename(decision.title, 'csv'));
  toast('Decision exported as CSV.');
}

/* -------------------------------- PDF ------------------------------------ */

const PDF_COLORS = {
  ink: [17, 26, 40],
  slate: [92, 107, 126],
  line: [227, 231, 237],
  petrol: [14, 107, 99],
  paper: [245, 246, 248],
  good: [30, 122, 70],
  warn: [169, 119, 11],
  risk: [178, 58, 47],
};

export function exportPDF(analysis, summaryText) {
  if (!window.jspdf?.jsPDF) {
    toast('PDF library did not load. Check your connection and retry.', 'error');
    return;
  }
  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 48;
    const contentW = pageW - margin * 2;
    const { ranked, confidence, flipPoints } = analysis;
    let y = 0;

    /* Header band */
    doc.setFillColor(...PDF_COLORS.ink);
    doc.rect(0, 0, pageW, 96, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(19);
    doc.text(fitLine(doc, decision.title || 'Decision analysis', contentW), margin, 44);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(200, 208, 218);
    doc.text(
      `Decision analysis · ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })} · Prepared with Choicease`,
      margin, 64,
    );
    if (decision.description) {
      doc.text(doc.splitTextToSize(decision.description, contentW).slice(0, 2), margin, 80);
    }
    y = 124;

    /* Verdict */
    doc.setTextColor(...PDF_COLORS.petrol);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('RECOMMENDATION', margin, y);
    y += 16;
    doc.setTextColor(...PDF_COLORS.ink);
    doc.setFontSize(14);
    const verdictLines = doc.splitTextToSize(verdictSentence(ranked, confidence), contentW);
    doc.text(verdictLines, margin, y);
    y += verdictLines.length * 17 + 6;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const confColor = confidence.level === 'High' ? PDF_COLORS.good
      : confidence.level === 'Medium' ? PDF_COLORS.warn : PDF_COLORS.risk;
    doc.setTextColor(...confColor);
    doc.text(`Confidence: ${confidence.level}`, margin, y);
    y += 18;

    /* Executive summary */
    doc.setTextColor(...PDF_COLORS.ink);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Executive summary', margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...PDF_COLORS.slate);
    for (const paragraph of (summaryText || '').split('\n\n')) {
      const lines = doc.splitTextToSize(paragraph, contentW);
      if (y + lines.length * 12 > 780) { doc.addPage(); y = 60; }
      doc.text(lines, margin, y);
      y += lines.length * 12 + 6;
    }
    y += 6;

    /* Ranking table with inline score bars */
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['#', 'Option', 'Score /5', 'Fit', '']],
      body: ranked.map((r) => [
        `${r.rank}${r.isTied ? '=' : ''}`,
        r.option.name,
        r.totalScore.toFixed(2),
        `${Math.round((r.totalScore / 5) * 100)}%`,
        '', // bar cell
      ]),
      styles: { font: 'helvetica', fontSize: 9, textColor: PDF_COLORS.ink, lineColor: PDF_COLORS.line, lineWidth: 0.5 },
      headStyles: { fillColor: PDF_COLORS.ink, textColor: [255, 255, 255], fontStyle: 'bold' },
      columnStyles: { 0: { cellWidth: 28 }, 2: { cellWidth: 56, halign: 'right' }, 3: { cellWidth: 44, halign: 'right' }, 4: { cellWidth: 130 } },
      didDrawCell: (data) => {
        if (data.section === 'body' && data.column.index === 4) {
          const r = ranked[data.row.index];
          const w = (r.totalScore / 5) * (data.cell.width - 8);
          doc.setFillColor(...(data.row.index === 0 ? PDF_COLORS.petrol : PDF_COLORS.slate));
          doc.rect(data.cell.x + 4, data.cell.y + data.cell.height / 2 - 3, Math.max(1, w), 6, 'F');
        }
      },
    });
    y = doc.lastAutoTable.finalY + 22;

    /* Criteria weights */
    ensureSpace(doc, y, 120); y = ensureSpace.lastY;
    sectionTitle(doc, 'Criteria and weights', margin, y); y += 8;
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Criterion', 'Weight', 'Description']],
      body: decision.criteria.map((c) => [
        c.name, `${Math.round(decision.normalizedWeights[c.id] || 0)}%`, c.description || '—',
      ]),
      styles: { font: 'helvetica', fontSize: 9, textColor: PDF_COLORS.ink, lineColor: PDF_COLORS.line, lineWidth: 0.5 },
      headStyles: { fillColor: PDF_COLORS.ink, textColor: [255, 255, 255], fontStyle: 'bold' },
      columnStyles: { 1: { cellWidth: 52, halign: 'right' } },
    });
    y = doc.lastAutoTable.finalY + 22;

    /* Ratings matrix */
    ensureSpace(doc, y, 140); y = ensureSpace.lastY;
    sectionTitle(doc, 'Score matrix (ratings 0–5)', margin, y); y += 8;
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Option', ...decision.criteria.map((c) => c.name), 'Score']],
      body: ranked.map((r) => [
        r.option.name,
        ...decision.criteria.map((c) => (r.criteriaScores[c.id]?.rating ?? 0).toFixed(1)),
        r.totalScore.toFixed(2),
      ]),
      styles: { font: 'helvetica', fontSize: 8, textColor: PDF_COLORS.ink, lineColor: PDF_COLORS.line, lineWidth: 0.5, halign: 'center' },
      headStyles: { fillColor: PDF_COLORS.ink, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
      columnStyles: { 0: { halign: 'left', fontStyle: 'bold' } },
    });
    y = doc.lastAutoTable.finalY + 22;

    /* Sensitivity */
    if (flipPoints.length && ranked.length > 1) {
      ensureSpace(doc, y, 120); y = ensureSpace.lastY;
      sectionTitle(doc, 'Sensitivity — flip points', margin, y); y += 8;
      doc.autoTable({
        startY: y,
        margin: { left: margin, right: margin },
        head: [['Criterion', 'Current weight', 'Flips at', 'New leader']],
        body: flipPoints.map((f) => [
          f.criterionName,
          `${Math.round(f.currentPct)}%`,
          f.flipAt === null ? 'Robust (0–100%)' : `${f.flipAt}%`,
          f.challenger || '—',
        ]),
        styles: { font: 'helvetica', fontSize: 9, textColor: PDF_COLORS.ink, lineColor: PDF_COLORS.line, lineWidth: 0.5 },
        headStyles: { fillColor: PDF_COLORS.ink, textColor: [255, 255, 255], fontStyle: 'bold' },
      });
      y = doc.lastAutoTable.finalY + 22;
    }

    /* Methodology */
    ensureSpace(doc, y, 110); y = ensureSpace.lastY;
    sectionTitle(doc, 'Methodology', margin, y); y += 14;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...PDF_COLORS.slate);
    const method = [
      'Weighted multi-criteria decision analysis. Importance ratings (1–5) map to geometric weights (1.0, 1.78, 3.16, 5.62, 10.0), normalized to 100%.',
      'Options rated 0–5 per criterion (0 = Unacceptable, 3 = Good, 5 = Excellent). Final score = Σ(rating × weight). Unrated cells default to 3.',
      'Sensitivity sweeps each criterion weight 0–100% (others rescaled proportionally) to locate exact flip points. Confidence reflects margin, flip distance, and rating coverage.',
      'Analysis performed entirely client-side; no data was transmitted. choicease.com',
    ];
    for (const line of method) {
      const wrapped = doc.splitTextToSize(`•  ${line}`, contentW);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 11 + 3;
    }

    /* Footer with page numbers */
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i += 1) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...PDF_COLORS.slate);
      doc.text('Choicease — smart choices, made easy · choicease.com', margin, 818);
      doc.text(`Page ${i} of ${pages}`, pageW - margin, 818, { align: 'right' });
    }

    doc.save(safeFilename(decision.title, 'pdf'));
    toast('Board-ready PDF downloaded.');
  } catch (err) {
    console.error('PDF export failed:', err);
    toast('PDF export failed. Try the CSV or JSON export instead.', 'error');
  }
}

function sectionTitle(doc, text, x, y) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...PDF_COLORS.ink);
  doc.text(text, x, y);
}

function ensureSpace(doc, y, needed) {
  if (y + needed > 790) {
    doc.addPage();
    ensureSpace.lastY = 60;
  } else {
    ensureSpace.lastY = y;
  }
}

function fitLine(doc, text, maxWidth) {
  const lines = doc.splitTextToSize(text, maxWidth);
  return lines.length > 1 ? `${lines[0].slice(0, -1)}…` : lines[0];
}

/* --------------------------------- QR ------------------------------------ */

const QR_CHUNK_SIZE = 1500;   // matches legacy exports
const QR_MAX_CHUNKS = 20;
const QR_VERSION = '1.1';

export async function exportQR() {
  if (!window.pako || !window.QRCode) {
    toast('QR libraries did not load. Check your connection and retry.', 'error');
    return;
  }
  try {
    const json = JSON.stringify(exportSnapshot());
    const compressed = window.pako.deflate(json);
    const base64 = u8ToBase64(compressed);

    const chunks = [];
    for (let i = 0; i < base64.length; i += QR_CHUNK_SIZE) {
      chunks.push(base64.slice(i, i + QR_CHUNK_SIZE));
    }
    if (chunks.length === 0) chunks.push(base64);
    if (chunks.length > QR_MAX_CHUNKS) {
      toast('This decision is too large for QR. Use the JSON export, or shorten descriptions.', 'warn');
      return;
    }

    const payloads = chunks.map((chunk, i) =>
      `${JSON.stringify({ i, t: chunks.length, v: QR_VERSION })}|${chunk}`);

    const canvases = [];
    for (const payload of payloads) {
      const canvas = document.createElement('canvas');
      await window.QRCode.toCanvas(canvas, payload, {
        errorCorrectionLevel: 'M',
        width: 560,
        margin: 2,
        color: { dark: '#111A28', light: '#FFFFFF' },
      });
      canvases.push(canvas);
    }

    const png = composeQRImage(canvases);
    downloadBlob(png, safeFilename(decision.title, 'png'));
    toast(canvases.length > 1
      ? `QR saved (${canvases.length} codes in one image). Import it any time.`
      : 'QR saved. Import it any time to restore this decision.');
  } catch (err) {
    console.error('QR export failed:', err);
    toast('QR export failed. Use the JSON export instead.', 'error');
  }
}

function composeQRImage(canvases) {
  const qrSize = 560;
  const pad = 36;
  const headerH = 104;
  const labelH = canvases.length > 1 ? 30 : 0;
  const width = qrSize + pad * 2;
  const height = headerH + canvases.length * (qrSize + labelH + pad) + pad;

  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, width, height);

  ctx.fillStyle = '#111A28';
  ctx.fillRect(0, 0, width, headerH);
  ctx.fillStyle = '#FFFFFF';
  ctx.font = '600 24px Arial, sans-serif';
  ctx.fillText(truncate(decision.title || 'Choicease decision', 38), pad, 44);
  ctx.fillStyle = '#B8C2CF';
  ctx.font = '400 15px Arial, sans-serif';
  ctx.fillText(`Saved ${new Date().toLocaleDateString()} · Import at choicease.com`, pad, 74);

  let y = headerH + pad;
  canvases.forEach((qr, index) => {
    if (labelH) {
      ctx.fillStyle = '#5C6B7E';
      ctx.font = '600 15px Arial, sans-serif';
      ctx.fillText(`Part ${index + 1} of ${canvases.length}`, pad, y + 8);
      y += labelH;
    }
    ctx.drawImage(qr, pad, y, qrSize, qrSize);
    y += qrSize + pad;
  });

  return dataURLToBlob(canvas.toDataURL('image/png'));
}

function truncate(text, max) {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

export function u8ToBase64(u8) {
  let binary = '';
  const CHUNK = 0x8000;
  for (let i = 0; i < u8.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, u8.subarray(i, i + CHUNK));
  }
  return btoa(binary);
}

function dataURLToBlob(dataURL) {
  const [meta, data] = dataURL.split(',');
  const mime = meta.match(/:(.*?);/)[1];
  const binary = atob(data);
  const u8 = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) u8[i] = binary.charCodeAt(i);
  return new Blob([u8], { type: mime });
}
